"""
scripts/materialize_features.py — Feast Feature Materialization
----------------------------------------------------------------
Materializes features from the offline Parquet store to the Redis
online store so the FastAPI service can look them up at prediction time.

Prerequisites:
  - Redis must be running           (docker compose up redis)
  - feast apply must have been run  (cd feast_repo && feast apply)
  - features.parquet must exist     (generated by training/train.py)

Usage:
  python scripts/materialize_features.py
"""

import os
import sys
import logging
from datetime import datetime, timezone

from feast import FeatureStore

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

FEAST_REPO_PATH = os.getenv(
    "FEAST_REPO_PATH",
    os.path.join(os.path.dirname(__file__), "..", "feast_repo"),
)


def materialize():
    logger.info(f"Connecting to Feast repo at: {FEAST_REPO_PATH}")
    store = FeatureStore(repo_path=FEAST_REPO_PATH)

    end_date = datetime.now(tz=timezone.utc)
    logger.info(f"Materializing features up to: {end_date.isoformat()}")

    try:
        store.materialize_incremental(end_date=end_date)
        logger.info("Feature materialization complete.")
    except FileNotFoundError as e:
        logger.error(
            f"features.parquet not found. Run training/train.py first.\n{e}"
        )
        sys.exit(1)
    except Exception as e:
        logger.error(f"Materialization failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    materialize()
